# Generated by Django 4.1.3 on 2022-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_video_views_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
