# Generated by Django 4.1.3 on 2022-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
